VERIFICAR_PINO_CONFIGURADO = 86
MOVER_PARA_FRENTE = "MF"
MOVER_PARA_TRAZ = "MT"
MOVER_PARA_DIREITA = "MD"
MOVER_PARA_ESQUERDA = "ME"
FAZER_CURVA = "MC"
MOTOR_PARAR = "MP" 
SENSOR_ULTRASSONICO = "UR"  