servidorUnoR4Wifi.ino
int teste
Variável de teste.
char ssid[][]
SSID da rede Wi-Fi.
Referenced by setup.
char pass[][]
Senha da rede Wi-Fi.
Referenced by setup.
WiFiUDP udp
Objeto UDP para comunicação Wi-Fi.
Referenced by setup.
unsigned int localPort
Porta local para comunicação UDP e TCP.
Referenced by setup.
char incomingPacket[255][255]
Buffer para pacotes UDP recebidos.
Referenced by setup.
bool pcConectado
Flag para indicar se um cliente está conectado.
Referenced by setup.
IPAddress pcIP
Endereço IP do cliente.
Referenced by setup.
unsigned int pcPort
Porta do cliente.
Referenced by setup.
WiFiClient client
Objeto do cliente TCP.
Referenced by ativarBuzzer, ativarBuzzerDelay, ativarLed, ativarLedDelay, ativarLedRGB, ativarLedRGBDelay, configurarBuzzer, configurarLedRGB, configurarLedSimples, configurarMotores, configurarPotenciometro, configurarPushButton, configurarSensorFotoresistor, configurarSensorOpticoReflexivo, configurarSensorUltrassonico, desativarLed, fazerCurva, inverterLed, lerSensorFotoresistor, lerSensorOpticoReflexivo, loop, setup, setVelocidade, verificarPinoConfigurado.
binaryFloat velocidade
Armazena a velocidade atual dos motores.
Referenced by getVelocidade, setup.
binaryFloat dado_retorno
Armazena os dados a serem retornados ao cliente.
Referenced by ativarBuzzer, ativarBuzzerDelay, ativarLed, ativarLedDelay, ativarLedRGB, ativarLedRGBDelay, configurarBuzzer, configurarLedRGB, configurarLedSimples, configurarMotores, configurarMPU, configurarPotenciometro, configurarPushButton, configurarSensorFotoresistor, configurarSensorOpticoReflexivo, configurarSensorUltrassonico, desativarBuzzer, desativarLed, desativarLedRGB, fazerCurva, getVelocidade, inverterLed, lerAcelerometroX, lerAcelerometroY, lerAcelerometroZ, lerBotao, lerGiroscopioX, lerGiroscopioY, lerGiroscopioZ, lerPotenciometro, lerSensorFotoresistor, lerSensorOpticoReflexivo, lerSensorUltrassonico, lerTemperatura, loop, pararMotores, resetarPinos, rotacionarDireita, rotacionarEsquerda, setup, setVelocidade, verificarPinoConfigurado.
const int MPU6050
Endereço I2C para comunicação com o sensor MPU6050.
Referenced by configurarMPU, lerAcelerometroX, lerAcelerometroY, lerAcelerometroZ, lerGiroscopioX, lerGiroscopioY, lerGiroscopioZ, lerTemperatura.
const float erro0
Código de erro para pino não configurado.
Referenced by ativarBuzzer, ativarBuzzerDelay, ativarLed, ativarLedDelay, ativarLedRGB, ativarLedRGBDelay, desativarBuzzer, desativarLed, desativarLedRGB, inverterLed, lerAcelerometroX, lerAcelerometroY, lerAcelerometroZ, lerBotao, lerGiroscopioX, lerGiroscopioY, lerGiroscopioZ, lerPotenciometro, lerSensorFotoresistor, lerSensorOpticoReflexivo, lerSensorUltrassonico, lerTemperatura.
const float erro1
Código de erro para parâmetro inválido.
Referenced by ativarLed, ativarLedDelay, ativarLedRGB, ativarLedRGBDelay, configurarBuzzer, configurarLedRGB, configurarLedSimples, configurarMotores, configurarPotenciometro, configurarPushButton, configurarSensorFotoresistor, configurarSensorOpticoReflexivo, configurarSensorUltrassonico, desativarLed, fazerCurva, inverterLed, lerSensorFotoresistor, lerSensorOpticoReflexivo, setVelocidade, verificarPinoConfigurado.
const float erro2
Código de erro para comando inválido.
Referenced by loop, setup.
byte PIN_ENA
Pino de ativação do Motor A (PWM).
Referenced by ativarBuzzer, ativarBuzzerDelay, ativarLed, ativarLedDelay, ativarLedRGB, ativarLedRGBDelay, configurarBuzzer, configurarLedRGB, configurarLedSimples, configurarMotores, configurarMPU, configurarPotenciometro, configurarPushButton, configurarSensorFotoresistor, configurarSensorOpticoReflexivo, configurarSensorUltrassonico, desativarBuzzer, desativarLed, desativarLedRGB, encerrarComunicacao, fazerCurva, inverterLed, lerAcelerometroX, lerAcelerometroY, lerAcelerometroZ, lerBotao, lerGiroscopioX, lerGiroscopioY, lerGiroscopioZ, lerPotenciometro, lerSensorFotoresistor, lerSensorOpticoReflexivo, lerSensorUltrassonico, lerTemperatura, loop, pararMotores, resetarPinos, rotacionarDireita, rotacionarEsquerda, setup, setVelocidade, verificarPinoConfigurado.
byte PIN_M1
Pino de controle 1 do Motor A.
Referenced by configurarMotores, pararMotores, resetarPinos, rotacionarDireita, rotacionarEsquerda, verificarPinoConfigurado.
byte PIN_M2
Pino de controle 2 do Motor A.
Referenced by configurarMotores, pararMotores, resetarPinos, rotacionarDireita, rotacionarEsquerda, verificarPinoConfigurado.
byte PIN_M3
Pino de controle 1 do Motor B.
Referenced by configurarMotores, pararMotores, resetarPinos, rotacionarDireita, rotacionarEsquerda, verificarPinoConfigurado.
byte PIN_M4
Pino de controle 2 do Motor B.
Referenced by configurarMotores, pararMotores, resetarPinos, rotacionarDireita, rotacionarEsquerda, verificarPinoConfigurado.
byte PIN_ENB
Pino de ativação do Motor B (PWM).
Referenced by configurarMotores, fazerCurva, resetarPinos, setup, setVelocidade, verificarPinoConfigurado.
byte PIN_ECHO
Pino ECHO do sensor ultrassônico.
Referenced by configurarSensorUltrassonico, lerSensorUltrassonico, resetarPinos, verificarPinoConfigurado.
byte PIN_TRIG
Pino TRIG do sensor ultrassônico.
Referenced by configurarSensorUltrassonico, lerSensorUltrassonico, resetarPinos, verificarPinoConfigurado.
byte PIN_LED1
Pino para o LED simples 1.
Referenced by ativarLed, ativarLedDelay, configurarLedSimples, configurarSensorOpticoReflexivo, desativarLed, inverterLed, resetarPinos, verificarPinoConfigurado.
byte PIN_LED2
Pino para o LED simples 2.
Referenced by ativarLed, ativarLedDelay, configurarLedSimples, configurarSensorOpticoReflexivo, desativarLed, inverterLed, resetarPinos, verificarPinoConfigurado.
byte PIN_LEDR
Pino do componente Vermelho (R) do LED RGB.
Referenced by ativarLedRGB, ativarLedRGBDelay, configurarLedRGB, desativarLedRGB, resetarPinos, verificarPinoConfigurado.
byte PIN_LEDG
Pino do componente Verde (G) do LED RGB.
Referenced by ativarLedRGB, ativarLedRGBDelay, configurarLedRGB, desativarLedRGB, resetarPinos, verificarPinoConfigurado.
byte PIN_LEDB
Pino do componente Azul (B) do LED RGB.
Referenced by ativarLedRGB, ativarLedRGBDelay, configurarLedRGB, desativarLedRGB, resetarPinos, verificarPinoConfigurado.
byte PIN_TONE
Pino para o buzzer.
Referenced by ativarBuzzer, ativarBuzzerDelay, configurarBuzzer, desativarBuzzer, resetarPinos, verificarPinoConfigurado.
byte PIN_FR1
Pino para o sensor fotorresistor 1.
Referenced by configurarSensorFotoresistor, lerSensorFotoresistor, lerSensorOpticoReflexivo, resetarPinos, verificarPinoConfigurado.
byte PIN_FR2
Pino para o sensor fotorresistor 2.
Referenced by configurarSensorFotoresistor, lerSensorFotoresistor, lerSensorOpticoReflexivo, resetarPinos, verificarPinoConfigurado.
byte PIN_OR1
Pino para o sensor óptico reflexivo 1.
Referenced by configurarSensorOpticoReflexivo, lerSensorOpticoReflexivo, resetarPinos, verificarPinoConfigurado.
byte PIN_OR2
Pino para o sensor óptico reflexivo 2.
Referenced by configurarSensorOpticoReflexivo, lerSensorOpticoReflexivo, resetarPinos, verificarPinoConfigurado.
byte PIN_OR3
Pino para o sensor óptico reflexivo 3.
Referenced by configurarSensorOpticoReflexivo, lerSensorOpticoReflexivo, resetarPinos, verificarPinoConfigurado.
byte PIN_PTC
Pino para o potenciômetro.
Referenced by configurarPotenciometro, lerPotenciometro, resetarPinos, verificarPinoConfigurado.
byte PIN_PBT
Pino para o botão de pressão (Push Button).
Referenced by configurarPushButton, lerBotao, resetarPinos, verificarPinoConfigurado.
byte PIN_MPU1
Pino SDA para o sensor MPU6050.
Referenced by configurarMPU, lerAcelerometroX, lerAcelerometroY, lerAcelerometroZ, lerGiroscopioX, lerGiroscopioY, lerGiroscopioZ, lerTemperatura, resetarPinos, verificarPinoConfigurado.
byte PIN_MPU2
Pino SCL para o sensor MPU6050.
Referenced by configurarMPU, lerAcelerometroX, lerAcelerometroY, lerAcelerometroZ, lerGiroscopioX, lerGiroscopioY, lerGiroscopioZ, lerTemperatura, resetarPinos, verificarPinoConfigurado.
dado_retorno floatingPoint
void resetarPinos()
Redefine todas as configurações de pino para seu estado padrão (não configurado) de 255. Também define o dado de retorno como 1 para indicar sucesso.
References dado_retorno, binaryFloat::floatingPoint, PIN_ECHO, PIN_ENA, PIN_ENB, PIN_FR1, PIN_FR2, PIN_LED1, PIN_LED2, PIN_LEDB, PIN_LEDG, PIN_LEDR, PIN_M1, PIN_M2, PIN_M3, PIN_M4, PIN_MPU1, PIN_MPU2, PIN_OR1, PIN_OR2, PIN_OR3, PIN_PBT, PIN_PTC, PIN_TONE, PIN_TRIG.
Referenced by setup.
void verificarPinoConfigurado()
Verifica a configuração de um pino específico. Lê um inteiro do cliente que corresponde ao pino de um componente específico. A função então define o dado de retorno para o número do pino configurado para aquele componente. Se o índice do componente for inválido, define o dado de retorno para um código de erro (erro1).
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ECHO, PIN_ENA, PIN_ENB, PIN_FR1, PIN_FR2, PIN_LED1, PIN_LED2, PIN_LEDB, PIN_LEDG, PIN_LEDR, PIN_M1, PIN_M2, PIN_M3, PIN_M4, PIN_MPU1, PIN_MPU2, PIN_OR1, PIN_OR2, PIN_OR3, PIN_PBT, PIN_PTC, PIN_TONE, PIN_TRIG.
Referenced by setup.
void configurarMotores()
Configura os pinos para os motores. Lê 6 números de pino do cliente para ENA, M1, M2, M3, M4 e ENB. Valida os números dos pinos (0-19) e, se forem válidos, os define como SAÍDA (OUTPUT). Se os números dos pinos forem inválidos, define um código de erro (erro1) e redefine os pinos do motor para 255.
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_ENB, PIN_M1, PIN_M2, PIN_M3, PIN_M4.
Referenced by setup.
void configurarSensorUltrassonico()
Configura os pinos para o sensor ultrassônico. Lê 2 números de pino do cliente para ECHO (ENTRADA) e TRIG (SAÍDA). Valida os números dos pinos (0-19). Se os números dos pinos forem inválidos, define um código de erro (erro1) e redefine os pinos do sensor para 255.
References client, dado_retorno, digitalWrite, erro1, binaryFloat::floatingPoint, PIN_ECHO, PIN_ENA, PIN_TRIG.
Referenced by setup.
void configurarLedSimples()
Configura o pino para um dos dois LEDs simples. Lê o número do LED (1 ou 2) e o número do pino do cliente. Valida o número do pino (0-19). Se os parâmetros forem inválidos, define um código de erro (erro1).
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LED1, PIN_LED2.
Referenced by setup.
void configurarLedRGB()
Configura os pinos para o LED RGB. Lê 3 números de pino do cliente para os componentes R, G e B (SAÍDA). Valida os números dos pinos (0-19). Se os números dos pinos forem inválidos, define um código de erro (erro1) e redefine os pinos do LED RGB para 255.
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LEDB, PIN_LEDG, PIN_LEDR.
Referenced by setup.
void configurarBuzzer()
Configura o pino para o buzzer. Lê 1 número de pino do cliente para o buzzer (SAÍDA). Valida o número do pino (0-19). Se o número do pino for inválido, define um código de erro (erro1) e redefine o pino do buzzer para 255.
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_TONE.
Referenced by setup.
void configurarSensorFotoresistor()
Configura o pino para um dos dois sensores fotorresistores. Lê o número do sensor (1 ou 2) e o número do pino do cliente. Valida o número do pino (0-19) e o define como ENTRADA (INPUT). Se os parâmetros forem inválidos, define um código de erro (erro1).
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_FR1, PIN_FR2.
Referenced by setup.
void configurarSensorOpticoReflexivo()
Configura o pino para um dos três sensores ópticos reflexivos. Lê o número do sensor (1, 2 ou 3) e o número do pino do cliente. Valida o número do pino (0-19). Os pinos para os sensores 1 e 2 são SAÍDA (OUTPUT), o pino para o sensor 3 é ENTRADA (INPUT). Se os parâmetros forem inválidos, define um código de erro (erro1).
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LED1, PIN_LED2, PIN_OR1, PIN_OR2, PIN_OR3.
Referenced by setup.
void configurarPotenciometro()
Configura o pino para o potenciômetro. Lê 1 número de pino do cliente para o potenciômetro (ENTRADA). Valida o número do pino (0-19). Se o número do pino for inválido, define um código de erro (erro1) e redefine o pino do potenciômetro para 255.
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_PTC.
Referenced by setup.
void configurarPushButton()
Configura o pino para o botão de pressão. Lê 1 número de pino do cliente para o botão de pressão (ENTRADA). Valida o número do pino (0-19). Se o número do pino for inválido, define um código de erro (erro1) e redefine o pino do botão de pressão para 255.
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_PBT.
Referenced by setup.
void configurarMPU()
Configura o sensor MPU6050. Inicializa a comunicação I2C com o MPU6050 e o ativa. Define as variáveis de pino internas para o MPU como 18 (SDA) e 19 (SCL).
References dado_retorno, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by setup.
void getVelocidade()
Obtém a velocidade atual do motor. A velocidade é armazenada em uma variável global e esta função a define como o dado de retorno.
References dado_retorno, binaryFloat::floatingPoint, velocidade.
Referenced by loop.
void setVelocidade()
Define a velocidade para ambos os motores. Lê dois valores de velocidade (0-255) do cliente para o motor A e o motor B.
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_ENB.
Referenced by loop.
<<<<<<< HEAD void andarParaFrente(){=======void andarParaTras(){ > > > > > > digitalWrite(PIN_M1, HIGH)
Referenced by ativarLed, ativarLedDelay, configurarSensorUltrassonico, desativarLed, inverterLed, lerSensorUltrassonico, pararMotores, rotacionarDireita, rotacionarEsquerda.
digitalWrite(PIN_M2, LOW)
digitalWrite(PIN_M3, HIGH)
digitalWrite(PIN_M4, LOW)
<<<<<<< HEAD void andarParaTras(){=======void andarParaFrente(){ > > > > > > digitalWrite(PIN_M1, LOW)
digitalWrite(PIN_M2, HIGH)
digitalWrite(PIN_M3, LOW)
digitalWrite(PIN_M4, HIGH)
void rotacionarEsquerda()
Rotaciona o robô para a esquerda.
References dado_retorno, digitalWrite, binaryFloat::floatingPoint, PIN_ENA, PIN_M1, PIN_M2, PIN_M3, PIN_M4.
Referenced by loop.
void rotacionarDireita()
Rotaciona o robô para a direita.
References dado_retorno, digitalWrite, binaryFloat::floatingPoint, PIN_ENA, PIN_M1, PIN_M2, PIN_M3, PIN_M4.
Referenced by loop.
void fazerCurva()
Faz o robô fazer uma curva definindo velocidades diferentes para cada motor. Lê dois valores de velocidade (v1, v2) do cliente para o motor A e o motor B. Valida que as velocidades estão no intervalo [0, 255].
References client, dado_retorno, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_ENB.
Referenced by loop.
void pararMotores()
Para ambos os motores.
References dado_retorno, digitalWrite, binaryFloat::floatingPoint, PIN_ENA, PIN_M1, PIN_M2, PIN_M3, PIN_M4.
Referenced by loop.
void ativarLed()
Ativa um LED simples. Lê o número do LED (1 ou 2) do cliente. Verifica se o pino do LED correspondente foi configurado.
References client, dado_retorno, digitalWrite, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LED1, PIN_LED2.
Referenced by loop.
void ativarLedDelay()
Ativa um LED simples por uma duração específica. Lê o número do LED (1 ou 2) e um tempo de atraso em milissegundos do cliente. O LED é ligado, o programa espera pelo tempo especificado e depois o LED é desligado. Verifica se o pino do LED correspondente foi configurado.
References client, dado_retorno, digitalWrite, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LED1, PIN_LED2.
Referenced by loop.
void inverterLed()
Inverte o estado de um LED simples. Lê o número do LED (1 ou 2) do cliente. Verifica se o pino do LED correspondente foi configurado.
References client, dado_retorno, digitalWrite, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LED1, PIN_LED2.
Referenced by loop.
void desativarLed()
Desativa um LED simples. Lê o número do LED (1 ou 2) do cliente. Verifica se o pino do LED correspondente foi configurado.
References client, dado_retorno, digitalWrite, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LED1, PIN_LED2.
Referenced by loop.
void ativarLedRGB()
Ativa o LED RGB com uma cor específica. Lê os valores R, G e B (0-255) do cliente. Verifica se os pinos do LED RGB foram configurados.
References client, dado_retorno, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LEDB, PIN_LEDG, PIN_LEDR.
Referenced by loop.
void ativarLedRGBDelay()
Ativa o LED RGB com uma cor específica por uma duração específica. Lê os valores R, G, B (0-255) e um tempo de atraso em milissegundos do cliente. O LED é ligado com a cor especificada, o programa espera e depois o LED é desligado. Verifica se os pinos do LED RGB foram configurados.
References client, dado_retorno, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_LEDB, PIN_LEDG, PIN_LEDR.
Referenced by loop.
void desativarLedRGB()
Desativa o LED RGB. Verifica se os pinos do LED RGB foram configurados.
References dado_retorno, erro0, binaryFloat::floatingPoint, PIN_ENA, PIN_LEDB, PIN_LEDG, PIN_LEDR.
Referenced by loop.
void ativarBuzzer()
Ativa o buzzer com uma frequência específica. Lê a frequência do cliente. Verifica se o pino do buzzer foi configurado.
References client, dado_retorno, erro0, binaryFloat::floatingPoint, PIN_ENA, PIN_TONE.
Referenced by loop.
void ativarBuzzerDelay()
Ativa o buzzer com uma frequência específica por uma duração específica. Lê a frequência e um tempo de atraso em milissegundos do cliente. O buzzer soa, o programa espera e então o buzzer para. Verifica se o pino do buzzer foi configurado.
References client, dado_retorno, erro0, binaryFloat::floatingPoint, PIN_ENA, PIN_TONE.
Referenced by loop.
void desativarBuzzer()
Desativa o buzzer. Verifica se o pino do buzzer foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, PIN_ENA, PIN_TONE.
Referenced by loop.
void lerSensorUltrassonico()
Lê a distância do sensor ultrassônico. Dispara o sensor e lê o pulso de eco para calcular a distância em centímetros. Verifica se os pinos do sensor ultrassônico foram configurados.
References dado_retorno, digitalWrite, erro0, binaryFloat::floatingPoint, PIN_ECHO, PIN_ENA, PIN_TRIG.
Referenced by loop.
void lerSensorFotoresistor()
Lê o valor de um sensor fotorresistor. Lê o número do sensor (1 ou 2) do cliente e retorna o valor analógico. Verifica se o pino do sensor correspondente foi configurado.
References client, dado_retorno, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_FR1, PIN_FR2.
Referenced by loop.
void lerSensorOpticoReflexivo()
Lê o valor de um sensor óptico reflexivo. Lê o número do sensor (1, 2 ou 3) do cliente e retorna o valor digital. Verifica se o pino do sensor correspondente foi configurado.
References client, dado_retorno, erro0, erro1, binaryFloat::floatingPoint, PIN_ENA, PIN_FR1, PIN_FR2, PIN_OR1, PIN_OR2, PIN_OR3.
Referenced by loop.
void lerPotenciometro()
Lê o valor do potenciômetro. Retorna o valor analógico. Verifica se o pino do potenciômetro foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, PIN_ENA, PIN_PTC.
Referenced by loop.
void lerBotao()
Lê o estado do botão de pressão. Retorna o valor digital. Verifica se o pino do botão de pressão foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, PIN_ENA, PIN_PBT.
Referenced by loop.
void lerTemperatura()
Lê a temperatura do sensor MPU6050. Retorna a temperatura em graus Celsius. Verifica se o MPU foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by loop.
void lerAcelerometroX()
Lê a aceleração do eixo X do sensor MPU6050. Retorna a aceleração em m/s^2. Verifica se o MPU foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by loop.
void lerAcelerometroY()
Lê a aceleração do eixo Y do sensor MPU6050. Retorna a aceleração em m/s^2. Verifica se o MPU foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by loop.
void lerAcelerometroZ()
Lê a aceleração do eixo Z do sensor MPU6050. Retorna a aceleração em m/s^2. Verifica se o MPU foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by loop.
void lerGiroscopioX()
Lê os dados do giroscópio do eixo X do sensor MPU6050. Retorna a velocidade angular em rad/s. Verifica se o MPU foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by loop.
void lerGiroscopioY()
Lê os dados do giroscópio do eixo Y do sensor MPU6050. Retorna a velocidade angular em rad/s. Verifica se o MPU foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by loop.
void lerGiroscopioZ()
Lê os dados do giroscópio do eixo Z do sensor MPU6050. Retorna a velocidade angular em rad/s. Verifica se o MPU foi configurado.
References dado_retorno, erro0, binaryFloat::floatingPoint, MPU6050, PIN_ENA, PIN_MPU1, PIN_MPU2.
Referenced by loop.
void encerrarComunicacao()
Reinicia a placa Arduino, encerrando efetivamente a comunicação.
References PIN_ENA.
Referenced by loop.
void setup()
Função de configuração, executada uma vez no início. Inicializa a comunicação serial, define a velocidade padrão, conecta-se ao WiFi. Em seguida, escuta por um broadcast UDP de um cliente para descoberta. Uma vez descoberto, aguarda uma conexão TCP do cliente. Após a conexão, entra em um loop de configuração onde o cliente pode configurar os pinos de hardware do robô antes do início da operação principal.
References binaryFloat::binary, client, configurarBuzzer, configurarLedRGB, configurarLedSimples, configurarMotores, configurarMPU, configurarPotenciometro, configurarPushButton, configurarSensorFotoresistor, configurarSensorOpticoReflexivo, configurarSensorUltrassonico, dado_retorno, erro2, binaryFloat::floatingPoint, incomingPacket, localPort, pass, pcConectado, pcIP, pcPort, PIN_ENA, PIN_ENB, resetarPinos, ssid, udp, velocidade, verificarPinoConfigurado.
void loop()
Loop principal, executado repetidamente. Verifica se há dados disponíveis do cliente TCP conectado. Lê os bytes de comando e chama a função apropriada para executar o comando. Após executar um comando, envia uma resposta de ponto flutuante de 4 bytes de volta para o cliente.
References ativarBuzzer, ativarBuzzerDelay, ativarLed, ativarLedDelay, ativarLedRGB, ativarLedRGBDelay, binaryFloat::binary, client, dado_retorno, desativarBuzzer, desativarLed, desativarLedRGB, encerrarComunicacao, erro2, fazerCurva, binaryFloat::floatingPoint, getVelocidade, inverterLed, lerAcelerometroX, lerAcelerometroY, lerAcelerometroZ, lerBotao, lerGiroscopioX, lerGiroscopioY, lerGiroscopioZ, lerPotenciometro, lerSensorFotoresistor, lerSensorOpticoReflexivo, lerSensorUltrassonico, lerTemperatura, pararMotores, PIN_ENA, rotacionarDireita, rotacionarEsquerda, setVelocidade.